### PR TITLE
Port to C++ and ReportEvent.

### PR DESCRIPTION
**Pull request by 0x7f**
Imho, using the win32 native API is more reliable than using clr/.Net in node bindings. That's why I ported the code to C++ and Nan (to get it running under latest node.js again).

### CODE REVIEW

**Comment by jfromaniello** [comment]
Looks nice, but to be honest, I don't understand your code since I am not familiar with C++ neither the win32 native API. 

Can I add you as a contributor/maintainer to this repo and the npm package so you can push directly?

**Comment by jfromaniello** [comment]
Done deal :)

**Comment by 0x7f** [comment]
Hehe, that was unexpected, but why not ;) Will clean up the commit again and let you know when I'm ready to merge so you can have a final look again.

**Comment by 0x7f** [comment]
Finally found a minute to clean up the commit a bit (improve error messages using `GetLastError()` and ensure formatting & naming is consistent). What do you think about the current state?

**Comment by 0x7f** [comment]
A thought about the external API: I'd like to make the `.log()` call async by default (in my experience WIN32 can block for ages sometimes depending on what they do) and add an additional `.logSync()` call if logging synchronously is required. But did not want to introduce this breaking change in this Pull Request already as it also requires updating dependent libraries like `winston-winlog`.
Whats your opinion about the breaking change?

**Comment by jfromaniello** [comment]
You can do it in this PR and release it as a major, no problem

**Comment by 0x7f** [comment]
Finally found a minute to introduce the async log function as well. Also bumped major version to 2.0 as discussed and moved some functionality to free function so they can be used by the `EventLogAsync` worker as well.

To be honest, I do not really know how the pre-built node modules work. Do you want to keep them? If so, could you please provide them, because I get a Security Exception on my machine when I try to run the powershell script.

**Comment by jfromaniello** [comment]
Good work!

I think we should remove the prebuilt stuff, is not a good practice to submit binaries to npm and most win devs are used to install the compiler on windows.

**Comment by 0x7f** [comment]
Alright, will remove them.

**Comment by 0x7f** [comment]
Done. Will squash the commits now to prepare them for merging.

**Comment by 0x7f** [comment]
Two things came to my mind that should be done before merging:
- README must be updated, will do so later today
- the severity could be made optional (default to info)

What do you think?

**Comment by jfromaniello** [comment]
@0x7f yes, I agree

**Comment by 0x7f** [comment]
@jfromaniello I updated the README and made the severity optional. Whats your opinion about the current state? Is it mergable?

**Comment by jfromaniello** [comment]
@0x7f looks wonderful!

**Pull request merged**
